# Generated by Django 5.2.5 on 2026-07-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveIntegerField(db_index=True)),
                ('imagen_original', models.ImageField(blank=True, null=True, upload_to='classifications/')),
                ('clase_predicha', models.CharField(choices=[('MADURO', 'Maduro'), ('INMADURO', 'Inmaduro'), ('REVISION', 'Revisión / Desconocido')], default='REVISION', max_length=20)),
                ('confianza', models.FloatField(default=0.0)),
                ('probabilidad_maduro', models.FloatField(default=0.0)),
                ('probabilidad_inmaduro', models.FloatField(default=0.0)),
                ('tiempo_preprocesamiento_ms', models.FloatField(default=0.0)),
                ('tiempo_inferencia_ms', models.FloatField(default=0.0)),
                ('latencia_total_ms', models.FloatField(default=0.0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('CLASIFICADO', 'Clasificado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='monitoring.lote')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['lote', 'secuencia'],
                'unique_together': {('lote', 'secuencia')},
            },
        ),
    ]
