# Generated by Django 5.2.5 on 2026-07-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_confianza', models.FloatField(default=0.8)),
                ('puerto_serial', models.CharField(default='COM3', max_length=50)),
                ('baudrate', models.PositiveIntegerField(default=9600)),
                ('modo_simulado', models.BooleanField(default=True)),
                ('angulo_maduro', models.PositiveIntegerField(default=45)),
                ('angulo_inmaduro', models.PositiveIntegerField(default=135)),
                ('angulo_neutral', models.PositiveIntegerField(default=90)),
                ('tiempo_compuerta_ms', models.PositiveIntegerField(default=2000)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='EventoHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=50)),
                ('respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('tiempo_respuesta_ms', models.FloatField(default=0.0)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_hardware', to='classification.clasificacion')),
            ],
            options={
                'verbose_name': 'Evento de Hardware',
                'verbose_name_plural': 'Eventos de Hardware',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
